Update assignmentRepository.ts
ERROR:
 error TS2352: Conversion of type 'ModifyResult<Document<unknown, {}, IAssignmentModel> & IAssignmentModel & { _id: ObjectId; }>' to type 'IAssignmentModel' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'ModifyResult<Document<unknown, {}, IAssignmentModel> & IAssignmentModel & { _id: ObjectId; }>' is missing the following properties from type 'IAssignmentModel': assignmentType, mainTopic, dueDate, title, and 57 more.